/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerArquivoBinario;
import controller.ControllerDepartamento;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import model.Departamento;
import model.DepartamentoTableModel;
import model.Efetivo;
import model.Funcionario;
import model.Substituto;
import model.Tecnico;

/**
 *
 * @author caiotavares
 */
public class JanPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanPrincipal
     */
    
    private ControllerArquivoBinario<Departamento> cbDepartamento = new ControllerArquivoBinario();

    
    public JanPrincipal() {
        initComponents();
    }
    
    public void mensagemTela(boolean confirmacao, String mensagem) {
        if (confirmacao) {
            JOptionPane.showMessageDialog(null, mensagem, "Confirmacao", 1);
        } else {
            JOptionPane.showMessageDialog(null, mensagem, "ERROR", 0);
        }
    }
    
    public void mensagemJTextDep(String mensagem) {
        jTextAreaDep.setText(cbDepartamento.getLista().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDepInfo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCarrArquivo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonInfoGeral = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TextNomeDep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ButtonCadastrarDep = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDep = new javax.swing.JTextArea();
        jButtonResDep = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldGastoMin = new javax.swing.JTextField();
        jTextFieldGastoMax = new javax.swing.JTextField();
        jButtonBuscaEntre = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldSalarioMin = new javax.swing.JTextField();
        jTextFieldSalarioMax = new javax.swing.JTextField();
        jButtonBuscaSalarioEntre = new javax.swing.JButton();
        jButtonTecRel = new javax.swing.JButton();
        jButtonDocRel = new javax.swing.JButton();
        jButtonDocEfetRel = new javax.swing.JButton();
        jButtonDocSubsRel = new javax.swing.JButton();
        jButtonDepInfo = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButtonFuncInfo = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldFuncInfo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldFuncInfoNome = new javax.swing.JTextField();
        jButtonFuncInfoNome = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxDep = new javax.swing.JComboBox<>();
        jButtonCarrDepList = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCadNomeTec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCadSalarioTec = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxCadNivelTec = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCadFuncaoTec = new javax.swing.JComboBox<>();
        jButtonCadTec = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCadNomeEfet = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCadSalarioEfet = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxCadNivelEfet = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxCadTitulacaoEfet = new javax.swing.JComboBox<>();
        jButtonCadEfet = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxCadAreaEfet = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldCadNomeSubs = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldCadSalarioSubs = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxCadNivelSubs = new javax.swing.JComboBox<>();
        jButtonCadSubs = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxCadHoraSubs = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxCadTitulacaoSubs = new javax.swing.JComboBox<>();
        jButtonMostrarFunc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFuncInfos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel1);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Departamentos");

        jLabel2.setText("código");

        jButtonCarrArquivo.setText("Carregar Arquivo");
        jButtonCarrArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrArquivoActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jButtonInfoGeral.setText("Geral");
        jButtonInfoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoGeralActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Cadastrar Departamento");

        TextNomeDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeDepActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome");

        ButtonCadastrarDep.setText("Cadastrar");
        ButtonCadastrarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNomeDep, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(118, 118, 118))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCadastrarDep)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNomeDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(ButtonCadastrarDep)
                .addContainerGap())
        );

        jTextAreaDep.setColumns(20);
        jTextAreaDep.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDep);

        jButtonResDep.setText("Resumo Departamento");
        jButtonResDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResDepActionPerformed(evt);
            }
        });

        jLabel21.setText("Gasto");

        jTextFieldGastoMin.setText("0");
        jTextFieldGastoMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldGastoMinKeyTyped(evt);
            }
        });

        jTextFieldGastoMax.setText("5000");
        jTextFieldGastoMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldGastoMaxKeyTyped(evt);
            }
        });

        jButtonBuscaEntre.setText("Buscar");
        jButtonBuscaEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaEntreActionPerformed(evt);
            }
        });

        jLabel25.setText("Departamento por gasto");

        jLabel26.setText("Funcionario por faixa salarial");

        jLabel27.setText("Salário");

        jTextFieldSalarioMin.setText("0");
        jTextFieldSalarioMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSalarioMinKeyTyped(evt);
            }
        });

        jTextFieldSalarioMax.setText("5000");
        jTextFieldSalarioMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSalarioMaxKeyTyped(evt);
            }
        });

        jButtonBuscaSalarioEntre.setText("Buscar");
        jButtonBuscaSalarioEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaSalarioEntreActionPerformed(evt);
            }
        });

        jButtonTecRel.setText("Relatório Técnicos");
        jButtonTecRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTecRelActionPerformed(evt);
            }
        });

        jButtonDocRel.setText("Relatório Docentes");
        jButtonDocRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocRelActionPerformed(evt);
            }
        });

        jButtonDocEfetRel.setText("Relatório Docentes Efetivos");
        jButtonDocEfetRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocEfetRelActionPerformed(evt);
            }
        });

        jButtonDocSubsRel.setText("Relatório Docentes Substitutos");
        jButtonDocSubsRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocSubsRelActionPerformed(evt);
            }
        });

        jButtonDepInfo.setText("Buscar");
        jButtonDepInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepInfoActionPerformed(evt);
            }
        });

        jLabel28.setText("Informações Departamento");

        jLabel29.setText("Relatórios");

        jButtonFuncInfo.setText("Buscar");
        jButtonFuncInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncInfoActionPerformed(evt);
            }
        });

        jLabel30.setText("código");

        jLabel31.setText("Informações Funcionário");

        jLabel32.setText("Nome");

        jButtonFuncInfoNome.setText("Buscar");
        jButtonFuncInfoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncInfoNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(416, 416, 416))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonCarrArquivo)
                        .addGap(614, 614, 614)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldGastoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldGastoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonBuscaEntre)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSalarioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSalarioMax, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel26)
                                    .addComponent(jButtonBuscaSalarioEntre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonTecRel)
                                    .addComponent(jButtonDocRel)
                                    .addComponent(jLabel29)
                                    .addComponent(jButtonDocSubsRel)
                                    .addComponent(jButtonDocEfetRel))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldDepInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel28)
                                            .addComponent(jButtonDepInfo))
                                        .addGap(85, 85, 85))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel31))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel30)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextFieldFuncInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jButtonFuncInfo))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonFuncInfoNome)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel32)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextFieldFuncInfoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonInfoGeral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonResDep)))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jButtonCarrArquivo)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInfoGeral)
                            .addComponent(jButtonResDep))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(jTextFieldGastoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldGastoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBuscaEntre))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel29))
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel27)
                                            .addComponent(jTextFieldSalarioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldSalarioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBuscaSalarioEntre))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButtonTecRel)
                                .addGap(9, 9, 9)
                                .addComponent(jButtonDocRel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDocEfetRel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDocSubsRel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDepInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDepInfo)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jTextFieldFuncInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jTextFieldFuncInfoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFuncInfo)
                            .addComponent(jButtonFuncInfoNome))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Departamento", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Departamento");

        jButtonCarrDepList.setText("Carregar");
        jButtonCarrDepList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrDepListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDep, 0, 183, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCarrDepList)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonCarrDepList)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Tecnico");

        jLabel7.setText("Nome");

        jLabel8.setText("Salario");

        jTextFieldCadSalarioTec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCadSalarioTecKeyTyped(evt);
            }
        });

        jLabel9.setText("Nível");

        jComboBoxCadNivelTec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T1", "T2" }));

        jLabel10.setText("Função");

        jComboBoxCadFuncaoTec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acessor", "Laboratório", "Funcionário" }));

        jButtonCadTec.setText("Cadastrar");
        jButtonCadTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadTecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCadSalarioTec, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxCadNivelTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCadNomeTec, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCadFuncaoTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadTec)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCadNomeTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCadSalarioTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxCadNivelTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxCadFuncaoTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadTec)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel11.setText("Efetivo");

        jLabel12.setText("Nome");

        jLabel13.setText("Salario");

        jTextFieldCadSalarioEfet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCadSalarioEfetKeyTyped(evt);
            }
        });

        jLabel14.setText("Nível");

        jComboBoxCadNivelEfet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D1", "D2", "D3" }));

        jLabel15.setText("Titulação");

        jComboBoxCadTitulacaoEfet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Mestrado", "Doutorado", "Livre-Docente", "Titular" }));

        jButtonCadEfet.setText("Cadastrar");
        jButtonCadEfet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEfetActionPerformed(evt);
            }
        });

        jLabel16.setText("Área");

        jComboBoxCadAreaEfet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biológicas", "Exatas", "Humanas", "Saúde", " " }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCadEfet))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCadSalarioEfet, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxCadNivelEfet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel11)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCadNomeEfet, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCadAreaEfet, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCadTitulacaoEfet, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldCadNomeEfet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldCadSalarioEfet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxCadNivelEfet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxCadTitulacaoEfet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxCadAreaEfet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButtonCadEfet)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel17.setText("Substituto");

        jLabel18.setText("Nome");

        jLabel19.setText("Salario");

        jTextFieldCadSalarioSubs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCadSalarioSubsKeyTyped(evt);
            }
        });

        jLabel20.setText("Nível");

        jComboBoxCadNivelSubs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1", "S2" }));

        jButtonCadSubs.setText("Cadastrar");
        jButtonCadSubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadSubsActionPerformed(evt);
            }
        });

        jLabel22.setText("Carga Horária");

        jComboBoxCadHoraSubs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24" }));

        jLabel23.setText("horas");

        jLabel24.setText("Titulação");

        jComboBoxCadTitulacaoSubs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Mestrado", "Doutorado", "Livre-Docente", "Titular" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCadSubs))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldCadSalarioSubs, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxCadNivelSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCadNomeSubs, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(30, 30, 30)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCadHoraSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCadTitulacaoSubs, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldCadNomeSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldCadSalarioSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBoxCadNivelSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBoxCadTitulacaoSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBoxCadHoraSubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadSubs)
                .addContainerGap())
        );

        jButtonMostrarFunc.setText("Todos os Funcionários");
        jButtonMostrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarFuncActionPerformed(evt);
            }
        });

        jTextAreaFuncInfos.setColumns(20);
        jTextAreaFuncInfos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaFuncInfos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMostrarFunc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMostrarFunc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Funcionarios", jPanel5);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCarrArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrArquivoActionPerformed
        // TODO add your handling code here:
        
        cbDepartamento.setArquivo("Abrir");
        if (cbDepartamento.getArquivo() == null) { //Caso o cara cancele na hora de abrir

        } else if (cbDepartamento.ler()) {
            mensagemTela(true, "Arquivo aceito!");
        } else {
            mensagemTela(false, "Error!");
        }
    }//GEN-LAST:event_jButtonCarrArquivoActionPerformed

    private void TextNomeDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeDepActionPerformed

    private void ButtonCadastrarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarDepActionPerformed
        if (TextNomeDep.getText().isEmpty()) {
            mensagemTela(false, "Precisa de nome!");
        } else {
            try {
                Departamento departamento = new Departamento(TextNomeDep.getText());
                cbDepartamento.getLista().add(departamento);
                if (cbDepartamento.escrever(false)) {
                    mensagemTela(true, "Cadastrado!");
                } else {
                    mensagemTela(false, "Erro ao cadastrar!");
                    if (JOptionPane.showConfirmDialog(this, "Gostaria de cadastrar?", "Cadastro", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        ButtonCadastrarDepActionPerformed(null);
                    }
                }
            } catch (Exception e) {
                mensagemTela(false, e.toString());
            } finally {
                TextNomeDep.setText("");
            }
        }
    }//GEN-LAST:event_ButtonCadastrarDepActionPerformed

    private void jButtonCarrDepListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrDepListActionPerformed
        // Listar departamentos
        List<Departamento> dep = cbDepartamento.getLista();

        jComboBoxDep.removeAllItems(); // Clear existing items

        for (Departamento departamento : dep) {
            jComboBoxDep.addItem(departamento.getNome()); // Add Departamento objects directly
        }
    }//GEN-LAST:event_jButtonCarrDepListActionPerformed

    private void jButtonCadTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadTecActionPerformed
        // CADASTRAR TECNICO
        List<Departamento> dep = cbDepartamento.getLista();
        
        String nome = jTextFieldCadNomeTec.getText();
        String nivel = (String) jComboBoxCadNivelTec.getSelectedItem();
        String funcao = (String) jComboBoxCadFuncaoTec.getSelectedItem();
        int salario = Integer.parseInt(jTextFieldCadSalarioTec.getText());
        
        if (jTextFieldCadNomeTec.getText().isEmpty() || jTextFieldCadSalarioTec.getText().isEmpty()) {
           mensagemTela(false, "Todos os campos devem estar prechidos!");
           return;
        }
        
        String selectedDepartamento = (String) jComboBoxDep.getSelectedItem();
        for (Departamento departamento : dep) {
            if (departamento.getNome().equals(selectedDepartamento)) {
                Funcionario tec = new Tecnico(
                    nome,
                    salario,
                    nivel,
                    funcao
                );
                
                ControllerDepartamento cd = new ControllerDepartamento();
                cd.adicionarFuncionario(tec, departamento);
                
                if (cbDepartamento.escrever(false)) {
                    mensagemTela(true, "Cadastrado!");
                    jTextFieldCadNomeTec.setText("");
                    jTextFieldCadSalarioTec.setText("");
                } else {
                    mensagemTela(false, "Erro ao cadastrar!");
                }
//                mensagemTela(false, tec.toString());
//                mensagemTela(false, departamento.toString());
            }
        }
    }//GEN-LAST:event_jButtonCadTecActionPerformed

    private void jTextFieldCadSalarioTecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCadSalarioTecKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCadSalarioTecKeyTyped

    private void jTextFieldCadSalarioEfetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCadSalarioEfetKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCadSalarioEfetKeyTyped

    private void jTextFieldCadSalarioSubsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCadSalarioSubsKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCadSalarioSubsKeyTyped

    private void jButtonCadEfetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEfetActionPerformed
        // Cadastrar Efetivo
        List<Departamento> dep = cbDepartamento.getLista();
        
        String nome = jTextFieldCadNomeEfet.getText();
        String titulacao = (String) jComboBoxCadTitulacaoEfet.getSelectedItem();
        String nivel = (String) jComboBoxCadNivelEfet.getSelectedItem();
        int salario = Integer.parseInt(jTextFieldCadSalarioEfet.getText());
        String area = (String) jComboBoxCadAreaEfet.getSelectedItem();
        
        if (jTextFieldCadNomeEfet.getText().isEmpty() || jTextFieldCadSalarioEfet.getText().isEmpty()) {
           mensagemTela(false, "Todos os campos devem estar prechidos!");
           return;
        }
        
        String selectedDepartamento = (String) jComboBoxDep.getSelectedItem();
        for (Departamento departamento : dep) {
            if (departamento.getNome().equals(selectedDepartamento)) {
                Funcionario efet = new Efetivo(
                    nome,
                    salario,
                    nivel,
                    titulacao,
                    area
                );
                
                ControllerDepartamento cd = new ControllerDepartamento();
                cd.adicionarFuncionario(efet, departamento);
                
                if (cbDepartamento.escrever(false)) {
                    mensagemTela(true, "Cadastrado!");
                    jTextFieldCadNomeEfet.setText("");
                    jTextFieldCadSalarioEfet.setText("");
                } else {
                    mensagemTela(false, "Erro ao cadastrar!");
                }
            }
        }
    }//GEN-LAST:event_jButtonCadEfetActionPerformed

    private void jButtonCadSubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadSubsActionPerformed
        List<Departamento> dep = cbDepartamento.getLista();
        
        String nome = jTextFieldCadNomeSubs.getText();
        String titulacao = (String) jComboBoxCadTitulacaoSubs.getSelectedItem();
        String nivel = (String) jComboBoxCadNivelSubs.getSelectedItem();
        int salario = Integer.parseInt(jTextFieldCadSalarioSubs.getText());
        int cargaHoraria = Integer.parseInt(jComboBoxCadHoraSubs.getSelectedItem().toString());
        
        if (jTextFieldCadNomeSubs.getText().isEmpty() || jTextFieldCadSalarioSubs.getText().isEmpty()) {
           mensagemTela(false, "Todos os campos devem estar prechidos!");
           return;
        }
        
        String selectedDepartamento = (String) jComboBoxDep.getSelectedItem();
        for (Departamento departamento : dep) {
            if (departamento.getNome().equals(selectedDepartamento)) {
                Funcionario subs = new Substituto(
                    nome,
                    salario,
                    nivel,
                    titulacao,
                    cargaHoraria
                );
                
                ControllerDepartamento cd = new ControllerDepartamento();
                cd.adicionarFuncionario(subs, departamento);
                
                if (cbDepartamento.escrever(false)) {
                    mensagemTela(true, "Cadastrado!");
                    jTextFieldCadNomeSubs.setText("");
                    jTextFieldCadSalarioSubs.setText("");
                } else {
                    mensagemTela(false, "Erro ao cadastrar!");
                }
            }
        }
    }//GEN-LAST:event_jButtonCadSubsActionPerformed

    private void jButtonMostrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarFuncActionPerformed
        List<Departamento> dep = cbDepartamento.getLista();
        
        String selectedDepartamento = (String) jComboBoxDep.getSelectedItem();
        for (Departamento departamento : dep) {
            if (departamento.getNome().equals(selectedDepartamento)) {
                jTextAreaFuncInfos.setText(departamento.getFuncionarios().toString());
            }
        }
    }//GEN-LAST:event_jButtonMostrarFuncActionPerformed

    private void jButtonInfoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoGeralActionPerformed
        mensagemJTextDep(cbDepartamento.getLista().toString());
    }//GEN-LAST:event_jButtonInfoGeralActionPerformed

    private void jButtonResDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResDepActionPerformed
        jTextAreaDep.setText(cbDepartamento.resumoDepartamentos());
    }//GEN-LAST:event_jButtonResDepActionPerformed

    private void jTextFieldGastoMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGastoMinKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldGastoMinKeyTyped

    private void jTextFieldGastoMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGastoMaxKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldGastoMaxKeyTyped

    private void jButtonBuscaEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaEntreActionPerformed
        // TODO add your handling code here:
        int min = Integer.parseInt(jTextFieldGastoMin.getText());
        int max = Integer.parseInt(jTextFieldGastoMax.getText());
        
        jTextAreaDep.setText(cbDepartamento.obterDepartamentosPorFaixaDeGasto(min, max).toString());
    }//GEN-LAST:event_jButtonBuscaEntreActionPerformed

    private void jTextFieldSalarioMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSalarioMinKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSalarioMinKeyTyped

    private void jTextFieldSalarioMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSalarioMaxKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSalarioMaxKeyTyped

    private void jButtonBuscaSalarioEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaSalarioEntreActionPerformed
        // TODO add your handling code here:
        int min = Integer.parseInt(jTextFieldSalarioMin.getText());
        int max = Integer.parseInt(jTextFieldSalarioMax.getText());
        
        jTextAreaDep.setText(cbDepartamento.funcionariosSalarioFaixa(min, max));
    }//GEN-LAST:event_jButtonBuscaSalarioEntreActionPerformed

    private void jButtonTecRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTecRelActionPerformed
        // TODO add your handling code here:
        
        jTextAreaDep.setText(cbDepartamento.tecnicoRelatorio());
    }//GEN-LAST:event_jButtonTecRelActionPerformed

    private void jButtonDocRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocRelActionPerformed
        // TODO add your handling code here:
        
        jTextAreaDep.setText(cbDepartamento.docenteRelatorio());
    }//GEN-LAST:event_jButtonDocRelActionPerformed

    private void jButtonDocEfetRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocEfetRelActionPerformed
        // TODO add your handling code here:
        
        jTextAreaDep.setText(cbDepartamento.docenteEfetivoRelatorio());
    }//GEN-LAST:event_jButtonDocEfetRelActionPerformed

    private void jButtonDocSubsRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocSubsRelActionPerformed
        // TODO add your handling code here:
        
        jTextAreaDep.setText(cbDepartamento.docenteSubstitutoRelatorio());
    }//GEN-LAST:event_jButtonDocSubsRelActionPerformed

    private void jButtonDepInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepInfoActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jTextFieldDepInfo.getText());
        jTextAreaDep.setText(cbDepartamento.departamentoInformacoes(codigo));
    }//GEN-LAST:event_jButtonDepInfoActionPerformed

    private void jButtonFuncInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncInfoActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jTextFieldFuncInfo.getText());
        jTextAreaDep.setText(cbDepartamento.funcionarioInformacoes(codigo));
    }//GEN-LAST:event_jButtonFuncInfoActionPerformed

    private void jButtonFuncInfoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncInfoNomeActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldFuncInfoNome.getText();
        jTextAreaDep.setText(cbDepartamento.funcionarioInformacoesNome(nome));
    }//GEN-LAST:event_jButtonFuncInfoNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrarDep;
    private javax.swing.JTextField TextNomeDep;
    private javax.swing.JButton jButtonBuscaEntre;
    private javax.swing.JButton jButtonBuscaSalarioEntre;
    private javax.swing.JButton jButtonCadEfet;
    private javax.swing.JButton jButtonCadSubs;
    private javax.swing.JButton jButtonCadTec;
    private javax.swing.JButton jButtonCarrArquivo;
    private javax.swing.JButton jButtonCarrDepList;
    private javax.swing.JButton jButtonDepInfo;
    private javax.swing.JButton jButtonDocEfetRel;
    private javax.swing.JButton jButtonDocRel;
    private javax.swing.JButton jButtonDocSubsRel;
    private javax.swing.JButton jButtonFuncInfo;
    private javax.swing.JButton jButtonFuncInfoNome;
    private javax.swing.JButton jButtonInfoGeral;
    private javax.swing.JButton jButtonMostrarFunc;
    private javax.swing.JButton jButtonResDep;
    private javax.swing.JButton jButtonTecRel;
    private javax.swing.JComboBox<String> jComboBoxCadAreaEfet;
    private javax.swing.JComboBox<String> jComboBoxCadFuncaoTec;
    private javax.swing.JComboBox<String> jComboBoxCadHoraSubs;
    private javax.swing.JComboBox<String> jComboBoxCadNivelEfet;
    private javax.swing.JComboBox<String> jComboBoxCadNivelSubs;
    private javax.swing.JComboBox<String> jComboBoxCadNivelTec;
    private javax.swing.JComboBox<String> jComboBoxCadTitulacaoEfet;
    private javax.swing.JComboBox<String> jComboBoxCadTitulacaoSubs;
    private javax.swing.JComboBox<String> jComboBoxDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaDep;
    private javax.swing.JTextArea jTextAreaFuncInfos;
    private javax.swing.JTextField jTextFieldCadNomeEfet;
    private javax.swing.JTextField jTextFieldCadNomeSubs;
    private javax.swing.JTextField jTextFieldCadNomeTec;
    private javax.swing.JTextField jTextFieldCadSalarioEfet;
    private javax.swing.JTextField jTextFieldCadSalarioSubs;
    private javax.swing.JTextField jTextFieldCadSalarioTec;
    private javax.swing.JTextField jTextFieldDepInfo;
    private javax.swing.JTextField jTextFieldFuncInfo;
    private javax.swing.JTextField jTextFieldFuncInfoNome;
    private javax.swing.JTextField jTextFieldGastoMax;
    private javax.swing.JTextField jTextFieldGastoMin;
    private javax.swing.JTextField jTextFieldSalarioMax;
    private javax.swing.JTextField jTextFieldSalarioMin;
    // End of variables declaration//GEN-END:variables
}
